source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CDJoystick_Example', :exclusive => true do
  pod "CDJoystick", :path => "../"
end

target 'CDJoystick_Tests', :exclusive => true do
  pod "CDJoystick", :path => "../"

  
end
